language: csharp

matrix:
   include:
     - os: linux # Ubuntu 14.04
       dist: trusty
       sudo: required
       dotnet: 2.0.2
     - os: osx # OSX 10.11
       osx_image: xcode7.3
       dotnet: 2.0.2

script:
  - ./build.sh All
